nav:
  - Overview: index.md
  - Porting information:
    - 1.17: porting-information/1.17.md
    - 1.18: porting-information/1.18.md
    - 1.19: porting-information/1.19.md
    - "1.20": porting-information/1.20.md
    - "1.21": porting-information/1.21.md
  - Mods:
    - Analyzer: analyzer/index.md
    - Boohoo!: boohoo/index.md
    - Curse of Curses: curse-of-curses/index.md
    - Data Trader: data-trader/index.md
    - Default World Type: defaultworldtype/index.md
    - Excavar: excavar/index.md
    - Just Enough Advancements: jea/index.md
    - LibX ðŸ”—: https://moddingx.org/wiki
    - NBT Remover: nbt-remover/index.md
    - Present Stand: present-stand/index.md
    - Skyblock Builder ðŸ”—: https://chaotictrials.github.io/SkyblockBuilder/
    - Yellow Snow: yellow-snow/index.md

site_name: MelanX's Mods Wiki
site_url: https://wiki.chaotictrials.de/

theme:
  palette:
    scheme: slate
    primary: light blue
    accent: lime
  name: material
  font:
    text: Jost
    code: Jetbrains Mono
  features:
    - tabs
  logo: assets/logo.png
  favicon: assets/logo.ico

markdown_extensions:
  - pymdownx.extra
  - codehilite:
      noclasses: true
      use_pygments: true
      pygments_style: monokai
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - fenced_code

plugins:
  - git-revision-date-localized:
      type: date

repo_name: ChaoticTrials/ModMeta
repo_url: https://github.com/ChaoticTrials/ModMeta
edit_uri: edit/wiki-source/docs/
